spring:  
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: kerich
    password: kerichfelix
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    logging:
      level:
        org.springframework.security: DEBUG

server:
  port: 8081