spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: kerich
    password: kerichfelix
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8082
